[package]
name = "python-binding"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[lib]
name = "binding"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.4.1", features = ["extension-module"] }
rand = "0.5.5"
rayon = "1.0.2"
