[package]
name = "gtk-tic-tac-toe"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
gtk = { version = "0.5.0", features = ["v3_22"] }
glib = "0.6.0"
gio = "0.5.0"
gdk = "0.9.0"
