[package]
name = "message-board"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["sqlite"] }
dotenv = "0.13.0"
