[package]
name = "name-derive"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.16"
quote = "0.6.9"
proc-macro2 = "0.4.20"
