[package]
name = "hastebin-client"
version = "0.1.0"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.3"
clap = "2.32.0"
serde = "1.0.80"
serde_derive = "1.0.80"
atty = "0.2.11"
